{- ZX Spectrum 48K rom charset.

License for fair use (not asking money for the ROM part) is allowed according to
signoff at http://www.worldofspectrum.org/permits/amstrad-roms.txt.
-}
module ZX.Data.Chars where

import Data.Char (chr, ord)
import ZX.Screen (sprite8, Sprite8)

stringToSprites :: String -> [Sprite8]
stringToSprites = map charToSprite

charToSprite :: Char -> Sprite8
charToSprite c
    | c < chr 32 || c > chr 127 = char_Question  -- Not in renderable range
    | otherwise = asciiPart !! (ord c - 32)

-- Below data generated by the rom-charset utility.

char_Space :: Sprite8
char_Space = sprite8 [0,0,0,0,0,0,0,0]

char_Exclamation :: Sprite8
char_Exclamation = sprite8 [0,16,16,16,16,0,16,0]

char_Quote :: Sprite8
char_Quote = sprite8 [0,36,36,0,0,0,0,0]

char_Hash :: Sprite8
char_Hash = sprite8 [0,36,126,36,36,126,36,0]

char_Dollar :: Sprite8
char_Dollar = sprite8 [0,8,62,40,62,10,62,8]

char_Percent :: Sprite8
char_Percent = sprite8 [0,98,100,8,16,38,70,0]

char_Amp :: Sprite8
char_Amp = sprite8 [0,16,40,16,42,68,58,0]

char_Apostrophe :: Sprite8
char_Apostrophe = sprite8 [0,8,16,0,0,0,0,0]

char_OpenParen :: Sprite8
char_OpenParen = sprite8 [0,4,8,8,8,8,4,0]

char_CloseParen :: Sprite8
char_CloseParen = sprite8 [0,32,16,16,16,16,32,0]

char_Star :: Sprite8
char_Star = sprite8 [0,0,20,8,62,8,20,0]

char_Plus :: Sprite8
char_Plus = sprite8 [0,0,8,8,62,8,8,0]

char_Comma :: Sprite8
char_Comma = sprite8 [0,0,0,0,0,8,8,16]

char_Dash :: Sprite8
char_Dash = sprite8 [0,0,0,0,62,0,0,0]

char_Dot :: Sprite8
char_Dot = sprite8 [0,0,0,0,0,24,24,0]

char_Slash :: Sprite8
char_Slash = sprite8 [0,0,2,4,8,16,32,0]

char_0 :: Sprite8
char_0 = sprite8 [0,60,70,74,82,98,60,0]

char_1 :: Sprite8
char_1 = sprite8 [0,24,40,8,8,8,62,0]

char_2 :: Sprite8
char_2 = sprite8 [0,60,66,2,60,64,126,0]

char_3 :: Sprite8
char_3 = sprite8 [0,60,66,12,2,66,60,0]

char_4 :: Sprite8
char_4 = sprite8 [0,8,24,40,72,126,8,0]

char_5 :: Sprite8
char_5 = sprite8 [0,126,64,124,2,66,60,0]

char_6 :: Sprite8
char_6 = sprite8 [0,60,64,124,66,66,60,0]

char_7 :: Sprite8
char_7 = sprite8 [0,126,2,4,8,16,16,0]

char_8 :: Sprite8
char_8 = sprite8 [0,60,66,60,66,66,60,0]

char_9 :: Sprite8
char_9 = sprite8 [0,60,66,66,62,2,60,0]

char_Colon :: Sprite8
char_Colon = sprite8 [0,0,0,16,0,0,16,0]

char_Semicolon :: Sprite8
char_Semicolon = sprite8 [0,0,16,0,0,16,16,32]

char_LeftBeak :: Sprite8
char_LeftBeak = sprite8 [0,0,4,8,16,8,4,0]

char_Equal :: Sprite8
char_Equal = sprite8 [0,0,0,62,0,62,0,0]

char_RightBeak :: Sprite8
char_RightBeak = sprite8 [0,0,16,8,4,8,16,0]

char_Question :: Sprite8
char_Question = sprite8 [0,60,66,4,8,0,8,0]

char_At :: Sprite8
char_At = sprite8 [0,60,74,86,94,64,60,0]

char_A :: Sprite8
char_A = sprite8 [0,60,66,66,126,66,66,0]

char_B :: Sprite8
char_B = sprite8 [0,124,66,124,66,66,124,0]

char_C :: Sprite8
char_C = sprite8 [0,60,66,64,64,66,60,0]

char_D :: Sprite8
char_D = sprite8 [0,120,68,66,66,68,120,0]

char_E :: Sprite8
char_E = sprite8 [0,126,64,124,64,64,126,0]

char_F :: Sprite8
char_F = sprite8 [0,126,64,124,64,64,64,0]

char_G :: Sprite8
char_G = sprite8 [0,60,66,64,78,66,60,0]

char_H :: Sprite8
char_H = sprite8 [0,66,66,126,66,66,66,0]

char_I :: Sprite8
char_I = sprite8 [0,62,8,8,8,8,62,0]

char_J :: Sprite8
char_J = sprite8 [0,2,2,2,66,66,60,0]

char_K :: Sprite8
char_K = sprite8 [0,68,72,112,72,68,66,0]

char_L :: Sprite8
char_L = sprite8 [0,64,64,64,64,64,126,0]

char_M :: Sprite8
char_M = sprite8 [0,66,102,90,66,66,66,0]

char_N :: Sprite8
char_N = sprite8 [0,66,98,82,74,70,66,0]

char_O :: Sprite8
char_O = sprite8 [0,60,66,66,66,66,60,0]

char_P :: Sprite8
char_P = sprite8 [0,124,66,66,124,64,64,0]

char_Q :: Sprite8
char_Q = sprite8 [0,60,66,66,82,74,60,0]

char_R :: Sprite8
char_R = sprite8 [0,124,66,66,124,68,66,0]

char_S :: Sprite8
char_S = sprite8 [0,60,64,60,2,66,60,0]

char_T :: Sprite8
char_T = sprite8 [0,254,16,16,16,16,16,0]

char_U :: Sprite8
char_U = sprite8 [0,66,66,66,66,66,60,0]

char_V :: Sprite8
char_V = sprite8 [0,66,66,66,66,36,24,0]

char_W :: Sprite8
char_W = sprite8 [0,66,66,66,66,90,36,0]

char_X :: Sprite8
char_X = sprite8 [0,66,36,24,24,36,66,0]

char_Y :: Sprite8
char_Y = sprite8 [0,130,68,40,16,16,16,0]

char_Z :: Sprite8
char_Z = sprite8 [0,126,4,8,16,32,126,0]

char_LeftBracket :: Sprite8
char_LeftBracket = sprite8 [0,14,8,8,8,8,14,0]

char_Backslash :: Sprite8
char_Backslash = sprite8 [0,0,64,32,16,8,4,0]

char_RightBracket :: Sprite8
char_RightBracket = sprite8 [0,112,16,16,16,16,112,0]

char_UpArrow :: Sprite8
char_UpArrow = sprite8 [0,16,56,84,16,16,16,0]

char_Underscore :: Sprite8
char_Underscore = sprite8 [0,0,0,0,0,0,0,255]

char_Pound :: Sprite8
char_Pound = sprite8 [0,28,34,120,32,32,126,0]

char_a :: Sprite8
char_a = sprite8 [0,0,56,4,60,68,60,0]

char_b :: Sprite8
char_b = sprite8 [0,32,32,60,34,34,60,0]

char_c :: Sprite8
char_c = sprite8 [0,0,28,32,32,32,28,0]

char_d :: Sprite8
char_d = sprite8 [0,4,4,60,68,68,60,0]

char_e :: Sprite8
char_e = sprite8 [0,0,56,68,120,64,60,0]

char_f :: Sprite8
char_f = sprite8 [0,12,16,24,16,16,16,0]

char_g :: Sprite8
char_g = sprite8 [0,0,60,68,68,60,4,56]

char_h :: Sprite8
char_h = sprite8 [0,64,64,120,68,68,68,0]

char_i :: Sprite8
char_i = sprite8 [0,16,0,48,16,16,56,0]

char_j :: Sprite8
char_j = sprite8 [0,4,0,4,4,4,36,24]

char_k :: Sprite8
char_k = sprite8 [0,32,40,48,48,40,36,0]

char_l :: Sprite8
char_l = sprite8 [0,16,16,16,16,16,12,0]

char_m :: Sprite8
char_m = sprite8 [0,0,104,84,84,84,84,0]

char_n :: Sprite8
char_n = sprite8 [0,0,120,68,68,68,68,0]

char_o :: Sprite8
char_o = sprite8 [0,0,56,68,68,68,56,0]

char_p :: Sprite8
char_p = sprite8 [0,0,120,68,68,120,64,64]

char_q :: Sprite8
char_q = sprite8 [0,0,60,68,68,60,4,6]

char_r :: Sprite8
char_r = sprite8 [0,0,28,32,32,32,32,0]

char_s :: Sprite8
char_s = sprite8 [0,0,56,64,56,4,120,0]

char_t :: Sprite8
char_t = sprite8 [0,16,56,16,16,16,12,0]

char_u :: Sprite8
char_u = sprite8 [0,0,68,68,68,68,56,0]

char_v :: Sprite8
char_v = sprite8 [0,0,68,68,40,40,16,0]

char_w :: Sprite8
char_w = sprite8 [0,0,68,84,84,84,40,0]

char_x :: Sprite8
char_x = sprite8 [0,0,68,40,16,40,68,0]

char_y :: Sprite8
char_y = sprite8 [0,0,68,68,68,60,4,56]

char_z :: Sprite8
char_z = sprite8 [0,0,124,8,16,32,124,0]

char_LeftBrace :: Sprite8
char_LeftBrace = sprite8 [0,14,8,48,8,8,14,0]

char_Pipe :: Sprite8
char_Pipe = sprite8 [0,8,8,8,8,8,8,0]

char_RightBrace :: Sprite8
char_RightBrace = sprite8 [0,112,16,12,16,16,112,0]

char_Tilde :: Sprite8
char_Tilde = sprite8 [0,20,40,0,0,0,0,0]

char_Copyright :: Sprite8
char_Copyright = sprite8 [60,66,153,161,161,153,66,60]

asciiPart :: [Sprite8]
asciiPart = [char_Space,char_Exclamation,char_Quote,char_Hash,char_Dollar,char_Percent,char_Amp,char_Apostrophe,char_OpenParen,char_CloseParen,char_Star,char_Plus,char_Comma,char_Dash,char_Dot,char_Slash,char_0,char_1,char_2,char_3,char_4,char_5,char_6,char_7,char_8,char_9,char_Colon,char_Semicolon,char_LeftBeak,char_Equal,char_RightBeak,char_Question,char_At,char_A,char_B,char_C,char_D,char_E,char_F,char_G,char_H,char_I,char_J,char_K,char_L,char_M,char_N,char_O,char_P,char_Q,char_R,char_S,char_T,char_U,char_V,char_W,char_X,char_Y,char_Z,char_LeftBracket,char_Backslash,char_RightBracket,char_UpArrow,char_Underscore,char_Pound,char_a,char_b,char_c,char_d,char_e,char_f,char_g,char_h,char_i,char_j,char_k,char_l,char_m,char_n,char_o,char_p,char_q,char_r,char_s,char_t,char_u,char_v,char_w,char_x,char_y,char_z,char_LeftBrace,char_Pipe,char_RightBrace,char_Tilde,char_Copyright]
